-- Using Inner Join to merge multiple tables
USE HR
GO

SELECT first_name, last_name,department_name,city,REGION_NAME FROM EMPLOYEES e INNER JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
INNER JOIN LOCATIONS l ON l.LOCATION_ID=d.LOCATION_ID INNER JOIN COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID
INNER JOIN REGIONS r ON c.REGION_ID = r.REGION_ID